// src/lib/components/layout/Footer.svelte
<script>
</script>

<footer>
  <p class="copyright">© Czenhe.</p>
</footer>

<style lang="scss">
  footer {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 12px;

    .copyright {
      font-size: 10px;
    }
  }

  @media (min-width: 480px) {
    footer {
      padding: 12px 0;
    }
  }
</style>

// src/components/layout/footer.vue
<template>
  <footer>
    <p class="copyright">© Czenhe.</p>
  </footer>
</template>

<style lang="scss">
  footer {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 12px;

    .copyright {
      font-size: 10px;
    }
  }

  @media (min-width: 480px) {
    footer {
      padding: 12px 0;
    }
  }
</style>
